spring:
  datasource:
    url: jdbc:mysql://139.196.194.172:3306/electric_bicycle_pro_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    userName: jjtest
    password: 99b39189a35c
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 10

  redis:
    database: 4
    host: 139.196.194.172
    password: test123
    port: 6380
    pool:
      max-active: 8
      max-wait: 1000
    timeout: 1000

eureka:
  client:
    service-url:
       defaultZone: http://139.196.194.172:8091/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
# LOGGING
logging:
    level:
       com.example: DEBUG
    config: classpath:logback/logback-dev.xml
