server:
  port: 2222


spring:
  application:
    name: jjbicycleuser
  profiles:
    active: dev
#    active: prod
  http:
    encoding:
      charset: utf-8
      enabled: true #是否开启http的编码支持
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  aop:
      proxy-target-class: true
  jmx:
    default-domain: wxapplet

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.appletper
  config-location: classpath:mybatis/mybatis.xml

logging:
    level:
    config: classpath:logback/logback-dev.xml

wxApplet.appId: wxd1cfbb46ce504c75
wxApplet.appSecret: b9ed8ecf76a6156455d9d0b6bcf46330
wxApplet.sessionTime: 1800
