server:
  port: 6666


spring:
  application:
    name: jjbicyclepay
  profiles:
#    active: local
#    active: dev
#    active: prod
     active: test
  http:
    encoding:
      charset: utf-8
      enabled: true #是否开启http的编码支持
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  aop:
      proxy-target-class: true
  jmx:
    default-domain: jjbicyclepay

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.appletper
  config-location: classpath:mybatis/mybatis.xml

logging:
    level:
    config: classpath:logback/logback-dev.xml


#分账账号
#格式 商户号;商户号;
splitMerInfo: 999991805302427;


