spring:
  datasource:
    url: jdbc:mysql://10.25.22.59:3306/electric_bicycle_pro_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    userName: jjtest
    password: 99b39189a35c
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 10

  redis:
    database: 4
    host: 10.25.22.59
    password: test123
    port: 6379
    pool:
      max-active: 8
      max-wait: 1000
    timeout: 1000

eureka:
  client:
    service-url:
       defaultZone: http://106.15.47.133:10000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
# LOGGING
logging:
    level:
       com.example: DEBUG
    config: classpath:logback/logback-dev.xml


#支付宝
newAliPay.partner: 2088031051855950
newAliPay.sellerId: tech@99bicycle.com
newAliPay.appId: 2018022602276452
newAliPay.privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD7g5BXVSmsttWoH4XZNM1FnIfpFwQ4Y8r2FR4pTAsz68BR0Y1sjMp/LTNpl03PJH5DA0buVGQibS9WHr767B90eaD76nARRpXwNMfpJypGmiI2bJyjhSFDne6REPnK8o1FjBDjgFKiqQ8LuSWZ/GxwjrKqn/svSl1fCPigj2D8ekAG9Rg7u1dC2xk9CFU2KNPGOm+I+xoWXLCJY03OIceFE44sH+q3/igdGV5PI3obJO8KwJpTcbWm7syn7h0nQTdk+CSWcntgT+N8v7zYyAw8lMVs1ERO8JGlGgbeDjpwx8DhA8PAync8IfoZyZwdEOkhGsQ0+8r1HmGLlndH9tVZAgMBAAECggEAa19NHZtjwTIEoFNkxsd94nvioaWLza78lHWLfMHT/oRkhAlbwL2SLRzU1/0Z4JaJuH4Lp+8rGG9YSAG0MlbfTtAl46W/1gA2Pmep+GUZ7S4b8PQJIt3Qx5cCo7eFjBhkKw6SnyzHGl3l6HFQFh7nBF5G9AR8LUIn/kxMJ+9Nzjpht4SOvOebGZhM4VYMY3PV7qSvwJt9ifxY9L1VYOwPgjITPeMDwwRnJHhBzNj+TEDAIHm9Xoe84JXCvjpXsmFXIt+FqsgkW0U88qgCMbFfWxoVvr4TlyNbpYS8OmAFOr7lhIPc6/lIaR54djb7+7pes5juARyL7V89xbQNwW5GoQKBgQD98gWxfRdCEXlT2Y89+vTDLgFaXERHOQQcovV3zyjnVLjJSa2E3lJGiu/quMSQB9Uk9X4+hP8NeJzCngSfSB/IB7mnBAR14PQCO88CJReFQlk/0fxAhlxQqcgqSh9byWFdevWK4kBWb2jAJ/Gh/OWrs4KxQ6gXMXKycJWMLuZppQKBgQD9jIFlq37zrKgmG55MH4Nmv0BczsS2TZAu36fF3wssAPq8P0yX09m4rjixac2Cd5raVzIXXJMXE5izt5/7HF8cWmIdqI5rp2vopdtKyAGyZjVKx+HIsx9rOoZZPwlj486yRwY2PE6vl3ZTNfrfnuAh57IVAp2R9v3gp0svYVlmpQKBgEFyMFlvvaC/VB9yAGKe3Jm4r4yUHtykKxUeQljgQNBtmzn1DQ0jJt0bTX2WpMHh4uKliiWerQTRwsS9aL+MHPS2WPhcJrIiiYBR3aXV3Vvwn4O9IF+YwQ3g079iXvaOzdMDr2hdqusbx0lOgg2XWbGIj/QTVay0h7TJIyF/rM4pAoGBAKk8f6I9Nh+vvwywophs8GhEf9Fyshp86yBeaL3Kgsp8XOAJ4DX3UfvTTkQdOu86pkHWsbimMgfVLLfIeSBDb7idG6BwQZ/ZwE0pZ5Yiqf9J+YhQooQ0C2SnS8WGLd5e0Dhu79aDqoHJt1ETVsCsay42WMdtV392PT8WazjU4beBAoGAV+whpqY584cDczqnQuMzS3V2vCI5l2QXJYrN9hzjCgDHvEG0RVIf3tb4WqndlbD7ugxP66dijW6QMvY+JBagdPr+JdRdkRctlItEltc2siqPs9OElVnYgAbvgAduC35ETJ36GijhRL+pD7/SkUd4c6ESf5hugoUbqhjbnsL87OQ=
newAliPay.appPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwkAYgo3zAhFHDXZqDI9gI/6J0++rrkZLXhlDxjYGhn7Eo+tyMbayADzPzYQ7l1KlIZk60TTMkJGoINAsa1aEZ6iIbrQEg/D+jS1Q+wYLqbY8aQpS7IiD+Lqq0wBGw9EqyCNh6zaAqZTX4d9jCoAyHxfYIAcQpRN9502t7gtWpinA5XDMzmTU5SiB5E7RWiR/I/TrKMxZL1MU5FZHoExDz/bvzPlCsNrgp6SXrkD8PeDhP4GiSES3AeBTg778XYhNsmf1/MaiNhj0MV5kvwndjF4mKnQaZtHslbkDN4yVppJ/nUTCP22JvOmjNCVpNY3aHoakI7gKcG52qkviNfbBRQIDAQAB
newAliPay.aliPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwkAYgo3zAhFHDXZqDI9gI/6J0++rrkZLXhlDxjYGhn7Eo+tyMbayADzPzYQ7l1KlIZk60TTMkJGoINAsa1aEZ6iIbrQEg/D+jS1Q+wYLqbY8aQpS7IiD+Lqq0wBGw9EqyCNh6zaAqZTX4d9jCoAyHxfYIAcQpRN9502t7gtWpinA5XDMzmTU5SiB5E7RWiR/I/TrKMxZL1MU5FZHoExDz/bvzPlCsNrgp6SXrkD8PeDhP4GiSES3AeBTg778XYhNsmf1/MaiNhj0MV5kvwndjF4mKnQaZtHslbkDN4yVppJ/nUTCP22JvOmjNCVpNY3aHoakI7gKcG52qkviNfbBRQIDAQAB
newAliPay.payBackUrl: http://47.100.131.56:6666/payback/alipayback
newAliPay.smsForRed: http://106.15.47.133:8080/sms/noticeSMS


#微信
wxPay.appId: wx5a008c78857c70ec
wxPay.mchId: 1461111202
wxPay.key: 43DBE8BC489BDC916DE00807BCB4B7D0
wxPay.packageSign: Sign=WXPay
wxPay.payBackUrl: http://47.100.131.56:6666/payback/wxpayback
wxPay.refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
wxPay.transferUrl: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
wxPay.cer: /home/cer/apiclient_cert.p12


#银联
chinaPayTestResURL: https://newpayment-test.chinapay.com/CTITS/service/rest/forward/syn/000000000017/0/0/0/0/0

#银联支付回调
chinaPayBackURL: http://47.100.131.56:6666/chinapay/payback


#银联代付
chinaPaySinPay: http://sfj-test.chinapay.com/dac/SinPayServletUTF8


